### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by goodmind** [goodmind/cycle-telegram#5]
```
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET', response: undefined }
```

**Comment by goodmind** [comment]
Related commit: 853d23a563c7d567a9cea5defcabbdfc01a9b41f
